#:kivy 1.10.0

<NetrunnerGame>:
	Grid
	Layout:
		cols 
		BoxLayout:
			orientation: 'vertical'

			Button:
				text: 'card'
			Button:
				text: 'card'
			Button:
				text: 'card'
			Button:
				text: 'card'
			Label:
				text: 'label'

		BoxLayout:
			orientation: 'vertical'
			Button:
				text: 'card'
		BoxLayout:
			orientation: 'vertical'
			Button:
				text: 'card'
		BoxLayout:
			orientation: 'vertical'
			Button:
				text: 'look at trashpile'
			Label:
				text: 'Trashpile'
